apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-learning-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-learning-platform
  template:
    metadata:
      labels:
        app: online-learning-platform
    spec:
      containers:
      - name: online-learning-platform
        image: your-dockerhub-username/online-learning-platform:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: online-learning-platform-service
spec:
  selector:
    app: online-learning-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
