apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-learning-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-learning-platform
  template:
    metadata:
      labels:
        app: online-learning-platform
    spec:
      containers:
      - name: online-learning-platform
        image: shandeep04/online-learning-platform:latest  # or use the tag from Jenkins
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: online-learning-platform-service
spec:
  type: ClusterIP
  selector:
    app: online-learning-platform
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
